### ISSUE TITLE
Why is Command Center SO FUCKING INCONSTANT

### ISSUE THREAD

**Issue by tobbep1997** [TheFlyingPandaa/BroodWarAI#1]
PLZ FIX ADMIN

**Comment by TheFlyingPandaa** [comment]
När mamma och pappa älskar varandra väldigt mycket. så byggs ett command center.
Ibland byggs det i ett hem. ibland byggs det i ett annat.
Sug min kuk är vad jag försöker säga:3

**Comment by tobbep1997** [comment]
Så nu är kuk sugen kan du fixa command center? 🤔

**Comment by TheFlyingPandaa** [comment]
Vi klarade kursen xD
Den funkade uppenbarligen xD
